### PR TITLE
Fix: Auto-expand file attachments accordion after upload - 2917

### LINKED ISSUE #2917: LCFS - BUG - File attachments accordion
**Describe the Bug**  
After uploading file attachments, the file attachment accordion remains collapsed, requiring the user to manually expand it to view the uploaded files. This extra step can be confusing and causes users to miss confirmation that their files were added successfully.

**Expected Behaviour**  
Once file attachments are added, the file attachment accordion should automatically expand to display the uploaded files without requiring additional user interaction.

**Actual Behaviour**  
The accordion stays collapsed after file upload, forcing the user to expand it manually to confirm the attachments are present.

**Implications**  
- Users may think their file uploads failed if they do not expand the accordion.  
- This creates unnecessary friction in the workflow and may result in duplicate uploads or user support requests.

**Steps To Reproduce**  
User/Role: Any user with access to file attachment functionality  
1. Upload a file in a section where attachments are added via an accordion UI.  
2. Observe that the accordion remains collapsed.  
3. Manually expand the accordion to confirm the file was uploaded.

**Notes**  
- Update UI logic to ensure the accordion expands automatically after a file is added.  
- Test the behavior across all relevant modules where file attachments are supported.

### PR DESCRIPTION
**Pull request by hamed-valiollahi**
This PR includes the fix to auto-expand the attachments accordion after uploading a file.  

Closes #2917

### CODE REVIEW

File: frontend/src/views/ComplianceReports/components/ReportDetails.jsx [hunk 1]
```diff
@@ -518,6 +524,24 @@ const ReportDetails = ({ canEdit, currentStatus = 'Draft', hasRoles }) => {
     []
   )
 
+  const prevHasDataRef = useRef(new Map())
+
+  useEffect(() => {
```
Comment (prv-proton) [inline frontend/src/views/ComplianceReports/components/ReportDetails.jsx:529]: @hamed-valiollahi, there's already an existing pattern implemented in this PR for handling this requirement in other schedules. You could consider following a similar approach for supporting documents to maintain consistency..
https://github.com/bcgov/lcfs/pull/2878/files

Comment (hamed-valiollahi) [reply frontend/src/views/ComplianceReports/components/ReportDetails.jsx:529]: Great! I reviewed the PR and it uses a much smarter pattern. I'll update the code. Thanks for pointing this out.

Comment (hamed-valiollahi) [reply frontend/src/views/ComplianceReports/components/ReportDetails.jsx:539]: Thanks for the review, Prashanth. I’ve updated the code to follow the same pattern we’re using in the other schedules. Let me know if you see any issues or if there’s anything else I should adjust.

File: frontend/src/views/ComplianceReports/EditViewComplianceReport.jsx [hunk 2]
```diff
@@ -613,32 +613,30 @@ export const EditViewComplianceReport = ({ isError, error }) => {
               chain={reportData?.chain}
             />
           </Stack>
-          {!location.state?.newReport && (
```
Comment (prv-proton) [inline frontend/src/views/ComplianceReports/EditViewComplianceReport.jsx:616]: removing this would show ComplianceReportSummary panel to the users. I think when a new Draft report is created we should only be showing introduction panel that's the reason this check was added.

Comment (hamed-valiollahi) [reply frontend/src/views/ComplianceReports/EditViewComplianceReport.jsx:616]: Thanks for the information. I kept the ComplianceReportSummary hidden for new draft reports, but made the ReportDetails visible so the supporting documents section shows up. This way, as soon as the user uploads a file, they can see it in draft mode.

**Comment by hamed-valiollahi** [comment]
> Looks good 👍

Thanks Prashanth for the code review.
