### PR TITLE
Fix: LCFS - BUG - Missing feature buttons IDIR analyst #2815

### LINKED ISSUE #2815: LCFS - BUG - Missing feature buttons IDIR analyst
**Describe the Bug**
The following features are missing for the IDIR Analyst:

**Early issuance Q4 year end report in Submitted status:**
missing Assessment statement feature and Analyst adjustment button

Image

**Early issuance Q4 year end report in Assessed status:**
missing Reassessment button

**Original report past March 31 in Subimitted:**
should have Create Supplemental report button, not Return to supplier

Image

### PR DESCRIPTION
**Pull request by prv-proton**
Fix #2815

- before creating any new compliance report ensure that the latest report is not in Draft status
- Refactor button configs as per the latest button matrix provided by Al.
- in order to not rely solely on cached data in case there are any changes, pass the status from list view to edit view and if there is any mismatch then refetch the report data.
- minor error handling

### CODE REVIEW

File: frontend/src/views/ComplianceReports/buttonConfigs.jsx [hunk 1]
```diff
@@ -1,334 +1,569 @@
...
+    }
+    return false
+  }
+}
+
+// =============================================================================
+// SIMPLIFIED BUTTON CONFIGURATION RULES
+// =============================================================================
+
+const BUTTON_RULES = {
```
Comment (AlexZorkin) [inline frontend/src/views/ComplianceReports/buttonConfigs.jsx:412]: This maps to the outline document nicely 👍

**Review by AlexZorkin — APPROVED** [review]
Pretty big refactor but nicely done. We'll have to let Al know about this so we can test the button config thoroughly 👍
