### PR TITLE
fix: create assessment report icon size

### LINKED ISSUE #2636: LCFS - BUG - Create supplemental report button icon
**Describe the Bug**  
The icon displayed within the “Create supplemental report” button is disproportionately small compared to standard UI elements. This was observed in the current interface and confirmed via screen capture.

**Expected Behaviour**  
The icon in the button should be visually balanced and consistent in size with other icons used in the application, maintaining a professional and accessible user interface.

**Actual Behaviour**  
The icon appears unusually small, making it visually unbalanced and harder to notice. This can detract from the overall usability and polish of the UI.
Image

**Implications**  
- Aesthetically inconsistent with the rest of the application.  
- May impact accessibility or reduce clarity of the button’s function.  
- Can reflect negatively on user experience and interface quality.

**Steps To Reproduce**  
User/Role: Any  
1. Navigate to a page containing the “Create Supplemental Report” button.  
2. Observe the icon size within the button compared to standard icon dimensions.

**Notes**  
- Adjust the icon size to align with established UI size conventions.  
- Verify rendering consistency across screen resolutions and browsers.  
- Coordinate with the UX team to confirm desired dimensions.

### PR DESCRIPTION
**Pull request by kevin-hashimoto**
- fix: icon size on the create supplemental report button, closes #2636

### CODE REVIEW

File: frontend/src/views/ComplianceReports/components/AssessmentCard.jsx [hunk 1]
```diff
@@ -176,7 +176,15 @@ export const AssessmentCard = ({
                           onClick={() => {
                             createSupplementalReport()
                           }}
-                          startIcon={<Assignment fontSize="1rem !important" />}
+                          startIcon={
+                            <Assignment
+                              fontSize="1rem !important"
```
Comment (hamed-valiollahi) [inline frontend/src/views/ComplianceReports/components/AssessmentCard.jsx:181]: I was able to change the icon size without using fontSize. Here’s my commit in case you want to check out the solution.

a296c3026e724705ae3476dc9650c0d5e86afe9a

**Review by hamed-valiollahi — APPROVED** [review]
Looks good to me! Thanks 👍
