### PR TITLE
fix: transaction id sorting

### LINKED ISSUE #2069: LCFS - BUG - Transaction ID Column Sorting Incorrect on BCeID and IDIR Transaction Pages
**Describe the Bug:**  
The **Transaction ID** column does not sort correctly on both the **BCeID** and **IDIR** transaction pages. Instead of sorting numerically, the IDs are sorted as text, leading to incorrect sequences such as **CR1, CR100, CR11** instead of **CR1, CR11, CR100**.  

**Expected Behaviour:**  
- The **Transaction ID** column should be sorted **numerically**, ensuring IDs appear in proper sequential order.  
- Sorting should maintain grouping by prefix.

**Actual Behaviour:**  
- Sorting treats transaction IDs as **text** rather than numbers.  
- Incorrect sequences occur, such as **CR1, CR100, CR11** instead of **CR1, CR11, CR100**.  

**Implications:**  
- Users cannot efficiently locate or track transactions.  
- Sorting inconsistencies may lead to reporting errors or confusion.  
- The issue affects **both BCeID and IDIR** users, impacting multiple roles.  

**Steps To Reproduce:**  
User/Role: **BCeID or IDIR**  
1. Navigate to the **Transactions** page.  
2. Click on the **Transaction ID** column to apply sorting.  
3. Observe that IDs are not sorted numerically but as text (e.g., **CR1, CR100, CR11**).  
4. Verify that sorting fails to follow expected numeric order while maintaining grouping by prefix.  

**Notes:**  
- Update sorting logic to recognize and **sort numeric values correctly**, even when prefixed (e.g., "CR").  
- Ensure sorting behaves correctly across different transaction ID formats.  
- Test sorting behavior across both **ascending and descending orders**.  
- Validate fix for **both BCeID and IDIR** transaction pages.

### PR DESCRIPTION
**Pull request by kevin-hashimoto**
- fix: transaction id not sorting correctly by numerical value, closes #2069 
- refactor: bc grid viewer to new bc grid viewer 2, touches on #2152

### CODE REVIEW

File: frontend/src/views/Transactions/_schema.js [hunk 1]
```diff
@@ -31,6 +31,12 @@ export const transactionsColDefs = (t) => [
     },
     filterParams: {
       buttons: ['clear']
+    },
+    comparator: (valueA, valueB) => {
+      const numberA = parseInt(valueA.slice(1), 10)
+      const numberB = parseInt(valueB.slice(1), 10)
+
+      return numberB - numberA
```
Comment (areyeslo) [inline frontend/src/views/Transactions/_schema.js:39]: is it possible to sort by the transactions at the repo level for each of the endpoints?

Comment (kevin-hashimoto) [reply frontend/src/views/Transactions/_schema.js:39]: I've implemented BCGridViewer2 so that we can have control of the sorting on the backend but even though we sort in the backend, ag grid will run a sort on the front end. so it looks like we will need this on the front end as well.

**Review by areyeslo — APPROVED** [review]
LGTM
