### PR TITLE
fix: compliance report summary compare label

### LINKED ISSUE #2534: LCFS - table header
**Describe the Bug**  
The "Non-compliance penalty payable" summary table in compare mode displays incorrect column headings. Specifically, two column headers do not match the expected headings from the equivalent summary tables above, leading to inconsistency in the report layout and potential confusion for users comparing data across sections.

Image

### PR DESCRIPTION
**Pull request by kevin-hashimoto**
- fix: fix: compliance report summary compare label, closes #2534

feel free to merge as I will be away until May 20th

### CODE REVIEW

File: frontend/src/views/CompareReports/CompareReports.jsx [hunk 1]
```diff
@@ -165,7 +165,7 @@ export const CompareReports = () => {
                 padding: '8px',
                 borderRadius: 1
               }}
-              value={report1ID}
+              // value={report1ID}
```
Comment (prv-proton) [inline frontend/src/views/CompareReports/CompareReports.jsx:168]: you might want to comment this in the other dropdown as well.

**Review by AlexZorkin — APPROVED** [review]
👍
