### PR TITLE
fix: default filter on filter reset

### LINKED ISSUE #1775: LCFS - Clearing filters results in BCeID users
Currently when navigating to the Users page as an IDIR user you will only see IDIR users.

* Click the Clear filter button
* Expected: Nothing changes
* Actual: BCeID users being to show

### PR DESCRIPTION
**Pull request by kevin-hashimoto**
- fix: filter reset clearing defaults, closes #1775

### CODE REVIEW

File: frontend/src/components/BCDataGrid/BCDataGridServer.jsx [hunk 1]
```diff
@@ -189,7 +189,7 @@ const BCDataGridServer = ({
     setPage(1)
     setSize(paginationPageSize)
     setSortModel(defaultSortModel || [])
-    setFilterModel([])
+    setFilterModel(defaultFilterModel || [])
```
Comment (prv-proton) [inline frontend/src/components/BCDataGrid/BCDataGridServer.jsx:192]: Would it be a good idea to move this logic to backend instead of frontend?

**Review by prv-proton — COMMENTED** [review]
Wouldn't it be good idea to move this logic to backend instead of frontend?

File: frontend/src/components/BCDataGrid/BCDataGridServer.jsx (hunk 1 above)
Comment (kevin-hashimoto) [reply frontend/src/components/BCDataGrid/BCDataGridServer.jsx:192]: i suppose you're right as this user endpoint only serves this one purpose. ill move the defaults to the backend

**Review by AlexZorkin — APPROVED** [review]
👍
