### PR TITLE
Fix: Notification action buttons - 2028

### LINKED ISSUE #2028: LCFS - Notification bug when "selecting all" and "deleting selected"
**Describe the Bug**
When a user selects "select all" and then "mark as read' this function works for **all pages** of notifications. When a user selects "select all" and the "delete selected" it only deletes the notifications on the page (so 10 lines at a time if the page size is 10, 25 at a time if it is a page size of 25, etc.). This happens for the IDIR and the BCeID side.

Image

**New Wireframe**  
[Notifications](https://preview.uxpin.com/e0e2f15fc1b52987fd0287ad8c8103452dd16d60#/pages/199531705?mode=dm)

**Expected Behaviour**
Once all "select all" is selected, this should apply to all notification lines, not just the ones on the page
- The red alert circle should disappear
- The notification count should reset to zero.

**Actual Behaviour**
- Only the notifications on the current page are being deleted, rather than all 
- The red alert circle remains visible on the bell icon, showing the notifications left on other pages

**Implications**
Users may think they still have new notifications, causing confusion.

**Steps To Reproduce**
Steps to reproduce the behaviour:
User/Role: IDIR

1. Open the notifications panel.
2. Click "Select all" and then "Delete selected"
3. Observe that only the notifications on the current page are deleted the bell icon still displays a red alert with a number.
4. Refresh the page and check if the issue persists.

### PR DESCRIPTION
**Pull request by hamed-valiollahi**
This PR includes the following fixes:
- Fixed "Select All" button functionality
- Fixed "Mark as Read" button functionality
- Fixed "Delete Selected" button functionality
- Fixed row-level delete icon not responding

Closes #2028

### CODE REVIEW

File: frontend/src/views/Notifications/NotificationMenu/components/Notifications.jsx [hunk 1]
```diff
@@ -170,7 +173,7 @@ export const Notifications = () => {
       ) {
         handleMutation(
           deleteMutation,
-          [params.data.notificationMessageId],
+          { notification_ids: [params.data.notificationMessageId] },
```
Comment (prv-proton) [inline frontend/src/views/Notifications/NotificationMenu/components/Notifications.jsx:176]: when a row is clicked, still facing issue with updating the row as read.
Request URL: http://localhost:8000/api/notifications/
Request Method: PUT
Status Code: 422 Unprocessable Entity
Payload: [97]

**Review by prv-proton — CHANGES_REQUESTED** [review]
Thanks @hamed-valiollahi , for fix most critical issues, just minor things 
- on click mark the row as read and navigate to respective page. (it's navigating but the row is not marked as read)
- Date filter within the grid is not working.

**Comment by hamed-valiollahi** [comment]
> Thanks @hamed-valiollahi , for fixing most critical issues, just minor things
> 
> * on click mark the row as read and navigate to respective page. (it's navigating but the row is not marked as read)
> * Date filter within the grid is not working.

Thanks @prv-proton for thorough testing. I've  applied the requested changes. 👍

**Review by prv-proton — APPROVED** [review]
Looks good 👍
